
export { default as authenticate         } from './authenticate'
export { default as signUp               } from './signUp'
export { default as getArtist            } from './getArtist'
export { default as getAlbum             } from './getAlbum'
export { default as getAuthenticatedUser } from './getAuthenticatedUser'
export { default as addLike              } from './addLike'
export { default as removeLike           } from './removeLike'
export { default as changePassword       } from './changePassword'
export { default as changeUsername       } from './changeUsername'
export { default as createArtist         } from './createArtist'
export { default as deleteArtist         } from './deleteArtist'
export { default as createAlbum          } from './createAlbum'
export { default as changeAlbumName      } from './changeAlbumName'
export { default as deleteAlbum          } from './deleteAlbum'
export { default as createSong           } from './createSong'
